# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\histogram_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from pyqtgraph import PlotWidget
import pyqtgraph

class Ui_HistogramWindow(object):
    window_closed = pyqtSignal()
    def setupUi(self, HistogramWindow):
        HistogramWindow.setObjectName("HistogramWindow")
        HistogramWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(HistogramWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.histogram = PlotWidget(self.centralwidget)
        self.histogram.setGeometry(QtCore.QRect(0, 0, 791, 541))
        self.histogram.setObjectName("histogram")
        HistogramWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HistogramWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        HistogramWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HistogramWindow)
        self.statusbar.setObjectName("statusbar")
        HistogramWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HistogramWindow)
        QtCore.QMetaObject.connectSlotsByName(HistogramWindow)
        
        self.histogram.setBackground("w")
        self.histogram.addLegend(offset=5)
        pen_h = pyqtgraph.mkPen(color='#8ECAE6', width=2)
        pen_s = pyqtgraph.mkPen(color='#FB8500', width=2)
        pen_v = pyqtgraph.mkPen(color= '#023047', width=2)
        self.h_plot = self.histogram.plot([0,0],[0, 0], name="hue", pen = pen_h)
        self.s_plot = self.histogram.plot([0,0],[0, 0], name="saturation", pen = pen_s)
        self.v_plot = self.histogram.plot([0,0],[0, 0], name="value", pen = pen_v)

    def closeEvent(self, event):
        print("close")
        self.window_closed.emit()
        # event.accept()

    def retranslateUi(self, HistogramWindow):
        _translate = QtCore.QCoreApplication.translate
        HistogramWindow.setWindowTitle(_translate("HistogramWindow", "Histogram"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HistogramWindow = QtWidgets.QMainWindow()
    ui = Ui_HistogramWindow()
    ui.setupUi(HistogramWindow)
    HistogramWindow.show()
    sys.exit(app.exec_())
